### ISSUE TITLE
Can't build for Windows 7

### ISSUE THREAD

**Issue by mightymarcus** [luboslenco/lue#11]
When I try to build the source files of a project in Visual Studio 13 for Win32 it gives 8 errors (on all examples and new blender projects):

error C2719: 'v': formal parameter with __declspec(align('16')) won't be aligned

When I try with x64 build it gives no errors, but it just show's an empty gray screen.

When I build from console with node Kha/make windows it gives some warnings.

my_project\build\temp\mesh.frag.hlsl(68,21): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

Kha Samples without zblend are working with Win32 and x64.

**Comment by mightymarcus** [comment]
"Native Bullet 3D Physics for Haxe. Includes library file for Kha. If you are having trouble getting generated c++ code to work, please use Haxe 3.2.0 or newer."

Oh oh ... I have to try later again.

**Comment by mightymarcus** [comment]
I've upgraded haxe to 3.2.0, but it doesn't work either.

**Comment by mightymarcus** [comment]
Now I tried a Linux build. When I start the build

Starting Kore
Reading project.kha
Could not open file project.kha.
Could not open file project.kha.

I think I am too silly ...

**Comment by luboslenco** [comment]
Oops missed this one, windows builds should now actually work. But not sure about Linux, will have to boot that up.

Let me know if windows works when you get a chance to test it:)

**Comment by luboslenco** [comment]
Spring cleaning - will provide proper getting started guide.
