### ISSUE TITLE
Licensing Problem

### ISSUE THREAD

**Issue by zauberparacelsus** [luboslenco/lue#12]
There's a bit of a problem with the licensing of zblend.  Blender is licensed under the GPL license, and because of this, any plugins written for it are required to be licensed GPL as well.  Or has zBlend been implemented in such a way that it doesn't directly use any of blender's code?

**Comment by luboslenco** [comment]
Hello,

Thanks for notice. The [blender plugin](https://github.com/luboslenco/zblend_blender) itself can be licensed under GPL, I think that should be sufficient? ZBlend itself is basically a standalone engine, which can be fed by blender plugin but doesn't depend on it.

Lubos

**Comment by zauberparacelsus** [comment]
Alright, thanks for the quick reply.  With that concern out of the way, I'm gonna start watching this project

**Comment by luboslenco** [comment]
Great! I am currently thinking on how to proceed, there are things in Blender which does not allow me to implement some features I want, so it is not yet recommend to use ZBlend as it may change a lot:)

**Comment by zauberparacelsus** [comment]
let me guess, one of those is particles?  IIRC, those aren't supported in BGE for some reason.

**Comment by luboslenco** [comment]
Main issue I have is implementing live game view directly in viewport, so you can quickly test game and edit while it's running. But this is of course not possible with python scripting only:)

**Comment by luboslenco** [comment]
Spring cleaning!
