### ISSUE TITLE
Any examples / Getting started docs? 

### ISSUE THREAD

**Issue by bradparks** [luboslenco/lue#16]
Hey...  I see some issues here talking about examples, but for zblend (which I assume was an old name for lue) 

Are there any current examples anywhere? The stuff you're showing on Twitter looks super cool ;-)

Thanks!

**Comment by luboslenco** [comment]
Hi Brad,

Thanks for tuning in! Yes, those are indeed all 'old'. The project has been rewritten from scratch, split into two parts - a core renderer, which I would like to make suitable for any realtime 3D application, and a Blender integration which sits on top.

No examples yet, but want to finally write a post this Sunday and start making stuff more accessible. :)

**Comment by zauberparacelsus** [comment]
I'm going to be looking forward to that :D

**Comment by bradparks** [comment]
Awesome... dont rush yourself on my account of course... but I'll watch for it as well... thanks and have a great weekend!

**Comment by luboslenco** [comment]
Ah, intro page is now ready!
http://luboslenco.com/notes/

Will continue the work on docs and examples. :)

**Comment by bradparks** [comment]
Cool.... thanks! I look forward to your release, but once again, no rush of course... you're doing some cool looking work!
