### ISSUE TITLE
Can't run the sample

### ISSUE THREAD

**Issue by alijaya** [luboslenco/lue#5]
Doing this http://docs.zblend.org/en/latest/Getting-started/ in MaxOS (10.9.3), Blender (2.71), Haxe (3.1.3), have succesfully fetch, but when press built, get this error in console

```
Error: Cannot find module './Tools/khamake/khamake.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Volumes/Home HD/Users/alijaya/Desktop/test/Kha/make.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by luboslenco** [comment]
Hello,

Hm that is strange, I am on OSX too and appears to work here. Are you trying on empty 'test.blend' project or is it one of the samples? Do you have node installed? Is it found when you open terminal and type 'node'?

Thanks,
Lubos

**Comment by alijaya** [comment]
I get test.blend from this repo https://github.com/luboslenco/zblend_project

yeah, I'm pretty sure that nodejs has been installed.

**Comment by alijaya** [comment]
Eh wait... suddenly I am able to run it :-?...
When I can't run it, I think it's because I fire up blender from terminal (because I want to see the console log).
But now, I fire blender normally (without terminal), when I hit run, it works!

Thanks btw for the support :D

**Comment by luboslenco** [comment]
Hm that is strange.. Also starting it from terminal here and it seems to work, dang! What 'way' do you use to boot it from terminal? Do you open blender executable located in blender .app directly?

Thanks for feedback! :)

**Comment by alijaya** [comment]
Yups... that's how I open it... is there any other way?

**Comment by luboslenco** [comment]
That's exactly how I do it also. I'm on OSX 10.10, not sure if it makes a difference. Will try on another mac machine.

**Comment by luboslenco** [comment]
Spring cleaning - the project is being reworked. :)
